-- NEXUS Trading System Database Schema
-- PostgreSQL 15+ optimized for time-series financial data

-- Connect to nexus_trading database
\c nexus_trading;

-- Grant permissions to nexus_user
GRANT ALL PRIVILEGES ON DATABASE nexus_trading TO nexus_user;
GRANT ALL ON SCHEMA public TO nexus_user;

-- Market data table (time-series optimized)
CREATE TABLE IF NOT EXISTS market_data (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    open DECIMAL(12,4),
    high DECIMAL(12,4),
    low DECIMAL(12,4),
    close DECIMAL(12,4),
    volume BIGINT,
    source VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Trading signals table
CREATE TABLE IF NOT EXISTS trading_signals (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    strategy_name VARCHAR(100) NOT NULL,
    signal_type VARCHAR(20) NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD')),
    confidence DECIMAL(3,2) CHECK (confidence >= 0 AND confidence <= 1),
    timestamp TIMESTAMP NOT NULL,
    price DECIMAL(12,4),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Backtest results table
CREATE TABLE IF NOT EXISTS backtest_results (
    id SERIAL PRIMARY KEY,
    strategy_name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_return DECIMAL(8,4),
    sharpe_ratio DECIMAL(6,4),
    max_drawdown DECIMAL(6,4),
    win_rate DECIMAL(5,4),
    total_trades INTEGER,
    parameters JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System health monitoring
CREATE TABLE IF NOT EXISTS system_health (
    id SERIAL PRIMARY KEY,
    component VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('HEALTHY', 'WARNING', 'ERROR')),
    metric_name VARCHAR(100),
    metric_value DECIMAL(10,4),
    message TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timestamp
    ON market_data(symbol, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_market_data_timestamp
    ON market_data(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_trading_signals_symbol_timestamp
    ON trading_signals(symbol, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_trading_signals_strategy
    ON trading_signals(strategy_name);

CREATE INDEX IF NOT EXISTS idx_backtest_results_strategy
    ON backtest_results(strategy_name);

CREATE INDEX IF NOT EXISTS idx_backtest_results_symbol
    ON backtest_results(symbol);

CREATE INDEX IF NOT EXISTS idx_system_health_timestamp
    ON system_health(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_system_health_component
    ON system_health(component);

-- Constraints and checks
ALTER TABLE market_data
    ADD CONSTRAINT chk_market_data_symbol_length
    CHECK (length(trim(symbol)) > 0);

ALTER TABLE market_data
    ADD CONSTRAINT chk_market_data_timestamp_not_future
    CHECK (timestamp <= CURRENT_TIMESTAMP + INTERVAL '1 day');

-- Comments for documentation
COMMENT ON TABLE market_data IS 'Time-series market data from various sources';
COMMENT ON TABLE trading_signals IS 'Trading signals generated by strategies';
COMMENT ON TABLE backtest_results IS 'Backtesting performance results';
COMMENT ON TABLE system_health IS 'System health monitoring and metrics';

-- Grant permissions on tables
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nexus_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO nexus_user;
